articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:article_id>/comments/create', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),

]

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta():
        model = Article
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        #fields = '__all__'
        #fields => 추가할 필드 이름 목록
        fields = ('content', )
        #-> content를 추가하고 보여주는 명령어
        #exclude => 제거할 필드 이름 목록
        #exclude = ('article', )
        #-> article을 제외하고 보여주는 명령어

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,

    }

    return render(request, 'index.html', context)

def detail(request, id):
    article = Article.objects.get(id=id)
    form = CommentForm()

    comments = Comment.objects.filter(article_id=id)

    context = {
        'article':article,
        'form': form,
        'comments': comments,
    }

    return render(request, 'detail.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', id=article.id)
    else:
        form = ArticleForm()

    context = {
        'form': form,
    }

    return render(request, 'form.html', context)

def comment_create(request, article_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)

            # 1. 객체(댓글?)를 저장하는 방법
            article = Article.objects.get(id=article_id)
            comment.article = article
            comment.save()

            # 2. integer(숫자)를 저장하는 방법
            comment.article_id = article_id
            comment.save()

            return redirect('articles:detail', id=article_id)

    else:
        return redirect('articles:index')

def comment_delete(request, article_id, id):
    if request.method == 'POST':
        comment = Comment.objects.get(id=id)
        comment.delete()
        
    return redirect('articles:detail', id=article_id)

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{article.title}}</h1>
    <p>{{article.content}}</p>

    <hr>
    <form action="{% url 'articles:comment_create' article_id=article.id %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
    <p>댓글 출력 방법 1</p>
    {% for comment in article.comment_set.all %}
        <li>{{comment.content}}</li>
        <form action="{% url 'articles:comment_delete' article_id=article.id id=comment.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="delete">
        </form>
    {% endfor %}

    <p>댓글 출력 방법 2</p>
    {% for comment in comments %}
        <li>{{comment.content}}</li>
    {% endfor %}

{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}

{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    {% for article in articles %}
        <p>{{article.title}}</p>
        <a href="{% url 'articles:detail' id=article.id %}">detail</a>
        <hr>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'articles:index' %}">home</a>
    <a href="{% url 'articles:create' %}">create</a>
    {% block body %}
    {% endblock %}
</body>
</html>